FROM ubuntu:18.04
WORKDIR /application
ENV DEBIAN_FRONTEND=noninteractive

ARG PYTHON_VERSION

RUN apt-get update && apt-get install -y software-properties-common gcc && \
    add-apt-repository -y ppa:deadsnakes/ppa


RUN apt-get update && apt-get install -y python3.8 python3-distutils python3-pip python3-apt


RUN apt-get install -y curl

RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py 
RUN python3.8 get-pip.py


RUN apt-get install -y python3.9

RUN apt install -y build-essential libssl-dev zlib1g-dev libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev libexpat1-dev liblzma-dev libffi-dev  uuid-dev

RUN python3 -m compileall .

RUN apt-get install -y pylint

RUN apt-get install -y python3-pip

RUN pip install -U pytest

RUN pip3 install pytest nbmake

RUN apt-get install -y python-dev

RUN apt install build-essential

RUN rm /usr/bin/python3
RUN ln -s /usr/bin/python3.8 /usr/bin/python3
